"""Noema Agent SDK.

Async, event-sourced, situation-aware primitives for autonomous agent systems.
"""

from .agent import AgentStatus, AutonomousAgent, AutonomousAgentConfig
from .attention import AttentionAccount, AttentionAllocator, AttentionWeights, WorkItem
from .authority import (
    ACTION_INTENT_JSON_SCHEMA,
    ActionIntent,
    AuthorityLevel,
    AuthorizationDecision,
    AutonomyProfile,
    PolicyEngine,
    RiskLevel,
    TrustEstimate,
    TrustLedger,
)
from .capabilities import (
    Capability,
    CapabilityContext,
    CapabilityRegistry,
    CapabilityResult,
    CapabilitySpec,
    FunctionCapability,
)
from .delivery import (
    EventBroker,
    InboxClaim,
    InboxConsumer,
    InboxDisposition,
    InMemoryBroker,
    OutboxPublisher,
    OutboxRecord,
    TransactionalDeliveryStore,
    event_topic,
)
from .deployment import Deployment, DeploymentMode, deployment_from_env
from .detectors import DeadlineRiskDetector, DetectorEngine, SituationDetector
from .events import (
    CURRENT_EVENT_SCHEMA_VERSION,
    AsyncEventBus,
    Event,
    EventSchemaRegistry,
)
from .kernel import NoemaKernel
from .models import (
    DELIBERATION_JSON_SCHEMA,
    ContextAssembler,
    DefaultContextAssembler,
    ModelCapabilities,
    ModelMessage,
    ModelProvider,
    ModelRequest,
    ModelResponse,
    ModelRouter,
    ModelUsage,
    RecordingModelProvider,
    ReplayModelProvider,
    StaticModelProvider,
    StructuredModelReasoner,
    model_request_fingerprint,
)
from .reasoning import (
    ActionOutcome,
    CapabilityExistenceCritic,
    CognitiveController,
    CognitiveMode,
    CompositeReasoner,
    Critic,
    Critique,
    DecisionTrace,
    DeliberationRequest,
    DeliberationResult,
    FalsificationCritic,
    Hypothesis,
    OpportunityCostCritic,
    Reasoner,
    RuleBasedReasoner,
)
from .scheduler import AsyncScheduler, ScheduleHandle
from .situation import (
    Commitment,
    CommitmentStatus,
    Entity,
    Fact,
    Goal,
    GoalStatus,
    Opportunity,
    Relation,
    Risk,
    SituationModel,
    SituationSnapshot,
)
from .store import EventStore, InMemoryEventStore, SQLiteEventStore, copy_events
from .system import NoemaSystem, RuntimeService
from .telemetry import InMemoryTelemetry, JsonlTelemetry, Metric, TelemetrySink
from .tracing import NullTracer, OpenTelemetryTracer, Span, Tracer

__all__ = [
    "ActionIntent",
    "ACTION_INTENT_JSON_SCHEMA",
    "ActionOutcome",
    "AgentStatus",
    "AsyncEventBus",
    "AsyncScheduler",
    "AttentionAccount",
    "AttentionAllocator",
    "AttentionWeights",
    "AuthorityLevel",
    "AuthorizationDecision",
    "AutonomousAgent",
    "AutonomousAgentConfig",
    "AutonomyProfile",
    "Capability",
    "CapabilityContext",
    "CapabilityExistenceCritic",
    "CapabilityRegistry",
    "CapabilityResult",
    "CapabilitySpec",
    "CognitiveController",
    "CognitiveMode",
    "Commitment",
    "CommitmentStatus",
    "CompositeReasoner",
    "Critic",
    "Critique",
    "DeadlineRiskDetector",
    "DELIBERATION_JSON_SCHEMA",
    "DecisionTrace",
    "DeliberationRequest",
    "DeliberationResult",
    "DetectorEngine",
    "Deployment",
    "DeploymentMode",
    "Entity",
    "Event",
    "EventBroker",
    "EventSchemaRegistry",
    "EventStore",
    "Fact",
    "FalsificationCritic",
    "FunctionCapability",
    "Goal",
    "GoalStatus",
    "Hypothesis",
    "InMemoryEventStore",
    "InMemoryBroker",
    "InMemoryTelemetry",
    "JsonlTelemetry",
    "Metric",
    "ModelCapabilities",
    "ModelMessage",
    "ModelProvider",
    "ModelRequest",
    "ModelResponse",
    "ModelRouter",
    "ModelUsage",
    "NoemaKernel",
    "NoemaSystem",
    "NullTracer",
    "Opportunity",
    "OpportunityCostCritic",
    "PolicyEngine",
    "OutboxPublisher",
    "OutboxRecord",
    "OpenTelemetryTracer",
    "InboxClaim",
    "InboxConsumer",
    "InboxDisposition",
    "RecordingModelProvider",
    "ReplayModelProvider",
    "Reasoner",
    "Relation",
    "Risk",
    "RiskLevel",
    "RuleBasedReasoner",
    "RuntimeService",
    "SQLiteEventStore",
    "ScheduleHandle",
    "SituationDetector",
    "SituationModel",
    "SituationSnapshot",
    "Span",
    "StaticModelProvider",
    "StructuredModelReasoner",
    "TelemetrySink",
    "Tracer",
    "TransactionalDeliveryStore",
    "TrustEstimate",
    "TrustLedger",
    "WorkItem",
    "copy_events",
    "CURRENT_EVENT_SCHEMA_VERSION",
    "ContextAssembler",
    "DefaultContextAssembler",
    "deployment_from_env",
    "event_topic",
    "model_request_fingerprint",
]

__version__ = "0.2.0"
