"""Learning-grade observation contracts for actual attention dispositions."""

from .models import (
    DELIBERATIVE_ATTENTION_EVENT_TYPES,
    DISPOSITION_FEEDBACK_RECORDED_EVENT,
    DISPOSITION_OUTCOME_LINKED_EVENT,
    DISPOSITION_RECORDED_EVENT,
    FEATURE_SCHEMA_RECORDED_EVENT,
    SOURCE_POLICY_RECORDED_EVENT,
    AttentionAuthorityCeiling,
    AttentionCostSnapshot,
    AttentionDenominatorAudit,
    AttentionDisposition,
    AttentionDispositionDecision,
    AttentionDispositionFeedbackRecord,
    AttentionDispositionOutcomeLink,
    AttentionDispositionRecord,
    AttentionFeatureDefinition,
    AttentionFeatureSchemaSnapshot,
    AttentionFeatureType,
    AttentionFeedback,
    AttentionOutcome,
    AttentionSourcePolicySnapshot,
    FeatureMissingness,
    OutcomeEvidenceClass,
    RecognizedAttentionOpportunity,
)
from .projection import AttentionExposureProjection
from .schemas import register_deliberative_attention_event_schemas
from .service import (
    AttentionDispositionProvider,
    AttentionOpportunity,
    AttentionSemanticConflictError,
    AttentionTelemetryContext,
    DeliberativeAttentionRecorder,
    DeliberativeAttentionWorker,
)

__all__ = [
    "DELIBERATIVE_ATTENTION_EVENT_TYPES",
    "DISPOSITION_FEEDBACK_RECORDED_EVENT",
    "DISPOSITION_OUTCOME_LINKED_EVENT",
    "DISPOSITION_RECORDED_EVENT",
    "FEATURE_SCHEMA_RECORDED_EVENT",
    "SOURCE_POLICY_RECORDED_EVENT",
    "AttentionAuthorityCeiling",
    "AttentionCostSnapshot",
    "AttentionDenominatorAudit",
    "AttentionDisposition",
    "AttentionDispositionDecision",
    "AttentionDispositionFeedbackRecord",
    "AttentionDispositionOutcomeLink",
    "AttentionDispositionProvider",
    "AttentionDispositionRecord",
    "AttentionExposureProjection",
    "AttentionFeatureDefinition",
    "AttentionFeatureSchemaSnapshot",
    "AttentionFeatureType",
    "AttentionFeedback",
    "AttentionOpportunity",
    "AttentionOutcome",
    "AttentionSemanticConflictError",
    "AttentionSourcePolicySnapshot",
    "AttentionTelemetryContext",
    "DeliberativeAttentionRecorder",
    "DeliberativeAttentionWorker",
    "FeatureMissingness",
    "OutcomeEvidenceClass",
    "RecognizedAttentionOpportunity",
    "register_deliberative_attention_event_schemas",
]
